# Generated by Django 3.1 on 2020-11-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20201031_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpu',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ram',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
