# Generated by Django 3.1 on 2020-11-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20201109_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='isFavourite',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='isFavourite',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='isFavourite',
        ),
    ]
