# Generated by Django 3.1 on 2020-11-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20201109_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='hardware_type',
            field=models.CharField(default='cpu', max_length=100),
        ),
        migrations.AddField(
            model_name='gpu',
            name='hardware_type',
            field=models.CharField(default='gpu', max_length=100),
        ),
        migrations.AddField(
            model_name='ram',
            name='hardware_type',
            field=models.CharField(default='ram', max_length=100),
        ),
    ]
