# Generated by Django 3.1 on 2021-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcGamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.IntegerField(default=0)),
                ('hard_disk', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('mother_board', models.CharField(max_length=100)),
                ('pc_case', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hardware_type', models.CharField(default='PcGamer', max_length=100)),
            ],
        ),
    ]
